title: nf-rnaSeqMetagen
description: A Nextflow pipeline for the identification and taxonomic classification of foreign/microbial reads reads from RNA-seq data.
show_downloads: false

# baseurl: "/docs"
# url: "https://phelelani.github.io/nf-rnaSeqMetagen/"

theme: jekyll-theme-cayman

author: Phelelani Mpangase

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow
